### ISSUE TITLE
[epgs] 一部の環境で映像が表示できない

### ISSUE THREAD

**Issue by ci7lus** [ci7lus/miraktest-plugins#3]
https://github.com/ci7lus/MirakTest/issues/12#issuecomment-934568809

@kilinbox さんの環境にて発現。

**Comment by kilinbox** [comment]
ログの調べ方ご教示ありがとうございます。
次のようなエラーになっていました。この192.168.55.5が私のEPGStationのアドレスです。
これを見るとポート番号とapiの間に「/」が二つあることからエラーになっているのではないかと思います。
プラグインの設定で、EPGStationのアドレスには「http://192.168.55.5:8888」と指定。
最後「/」で終わらない場合もログを見ると「//」となっていました。

> main.js:8 URL再生: http://192.168.55.5:8888//api/videos/45
> main.js:8 再生開始 http://192.168.55.5:8888//api/videos/45
> main.js:8 Creating an input for '45'
> main.js:8 using timeshift granularity of 50 MiB
> main.js:8 using default timeshift path
> main.js:8 `http://192.168.55.5:8888//api/videos/45' gives access `http' demux `any' path `192.168.55.5:8888//api/videos/45'
> main.js:8 creating demux: access='http' demux='any' location='192.168.55.5:8888//api/videos/45' file='(null)'
> main.js:8 looking for access_demux module matching "http": 14 candidates
> main.js:8 no access_demux modules matched
> main.js:8 creating access: http://192.168.55.5:8888//api/videos/45
> main.js:8 looking for access module matching "http": 24 candidates
> main.js:8 resolving 192.168.55.5 ...
> main.js:8 outgoing request:
> GET //api/videos/45 HTTP/1.1
> Host: 192.168.55.5:8888
> Accept: */*
> Accept-Language: en_US
> User-Agent: VLC/3.0.14 LibVLC/3.0.14
> Range: bytes=0-
> 
> main.js:8 incoming response:
> HTTP/1.1 404 Not Found
> X-Powered-By: Express
> Access-Control-Allow-Origin: *
> Content-Security-Policy: default-src 'none'
> X-Content-Type-Options: nosniff
> Content-Type: text/html; charset=utf-8
> Content-Length: 153
> Date: Tue, 05 Oct 2021 16:56:55 GMT
> Connection: keep-alive
> Keep-Alive: timeout=5
> 
> main.js:8 HTTP 404 error
> main.js:8 querying proxy for http://192.168.55.5:8888//api/videos/45
> main.js:8 no proxy
> main.js:8 http: server='192.168.55.5' port=8888 file='//api/videos/45'
> main.js:8 net: connecting to 192.168.55.5 port 8888
> main.js:8 connection succeeded (socket = 27)
> main.js:8 sending request:
> GET //api/videos/45 HTTP/1.0
> Host: 192.168.55.5:8888
> User-Agent: VLC/3.0.14 LibVLC/3.0.14
> Icy-MetaData: 1
> 
> main.js:8 HTTP answer code 404
> main.js:8 error: HTTP/1.1 404 Not Found
> main.js:8 no access modules matched
> main.js:8 Your input can't be opened
> main.js:8 Creating an input for '45'
> main.js:8 using timeshift granularity of 50 MiB
> main.js:8 using default timeshift path

**Comment by ci7lus** [comment]
修正してみたので、 https://github.com/ci7lus/miraktest-plugins/releases/tag/2021100612  お試しいたけますか！

**Comment by kilinbox** [comment]
> 修正してみたので、 https://github.com/ci7lus/miraktest-plugins/releases/tag/2021100612 お試しいたけますか！

確認しました。無事、正常に録画番組が再生できました。
ご対応ありがとうございました。
