### ISSUE TITLE
[epgs] 録画一覧より視聴する場合、mp4ファイル等は再生不可

### ISSUE THREAD

**Issue by shirow-github** [ci7lus/miraktest-plugins#6]
MirakTest  2.0.0-beta.4 for Windows 10
miraktest-epgs 2022020421
Epgstation v2.6.20
Mirakurun 3.9.0-rc.1

「プラグイン」→「EpgStation 録画一覧」→「視聴」をクリックしても、x264にエンコード済みのmp4録画ファイルが再生出来ません。
試しに、素のTSファイルは再生可能です。

確認のほど、よろしくお願い致します。

**Comment by ci7lus** [comment]
EPGStationのエンコード機能を使ったことがなく勘での対応となるのですが、`videoFiles`にmp4が入ってるのかなと予想して再生ファイルを選べるようにしてみました。治っていればクローズお願いします〜！
https://github.com/ci7lus/miraktest-plugins/releases/tag/2022020819

**Comment by shirow-github** [comment]
早速の対応ありがとうございます。

TSもmp4も、問題なく再生することが出来ました。

ありがとうございました。
